export const TRANSFER_KEYWORDS = [
  'transfer',
  'savings transfer',
  'monthly savings',
  'internal transfer',
  'account transfer',
  'between accounts',
  'tfr',
  'transfer to',
  'transfer from',
  'own account',
  'fund transfer',
  'bank transfer',
  'wire transfer',
  'wallet load',
  'topup',
  'top-up',
  'connectips',
  'swift transfer',
  'neft',
  'rtgs',
  'esewa topup',
  'esewa load',
  'khalti load',
  'ime pay load',
  'fonepay transfer',
  'connectips debit',
  'mobile banking transfer',
  'bachat transfer',
  'chalti to bachat',
  'fd transfer',
  'prabhu transfer',
  'nabil transfer',
  'nic asia transfer',
];

export const INVESTMENT_KEYWORDS = [
  'investment',
  'invest',
  'etf',
  'vgs',
  'vas',
  'stocks',
  'brokerage',
  'crypto',
  'bitcoin',
  'stock purchase',
  'equity',
  'vanguard',
  'fidelity',
  'blackrock',
  'index fund',
  'mutual fund',
  'etf fund',
  'stock shares',
  'share purchase',
  'btc',
  'ethereum',
  'eth',
  'binance',
  'coinbase',
  'gold purchase',
  'silver',
  'commodity',
  'ipo',
  'rights share',
  'fd',
  'fixed deposit',
  'nepse',
  'tms',
  'demat',
  'ipo application',
  'merolagani',
  'sharesansar',
  'cdsc',
  'meroshare',
  'mutual fund nepal',
  'nabil invest',
  'nlic',
  'lagani',
  'sip',
  'systematic investment',
  'laxmi sunrise',
];

export const REFUND_KEYWORDS = [
  'refund',
  'reimbursement',
  'cashback',
  'cash back',
  'reversal',
  'chargeback',
  'return credit',
  'money back',
  'adjustment credit',
  'credit note',
  'firta',
  'wapas',
  'return payment',
  'esewa refund',
  'khalti refund',
  'daraz refund',
  'refund credit',
  'reward',
];

export const INCOME_HIGH_KEYWORDS = [
  'salary',
  'wage',
  'wages',
  'payroll',
  'revenue',
  'bonus',
  'commission',
  'dividend',
  'grant',
  'stipend',
  'pension',
  'benefit',
  'allowance',
  'direct deposit',
  'employment income',
  'freelance',
  'consulting fee',
  'contract payment',
  'invoice payment',
  'incentive',
  'performance pay',
  'interest credit',
  'byaj',
  'interest earned',
  'byaj credit',
  'bachat byaj',
  'rental income',
  'tenant payment',
  'lease income',
  'cashback bonus',
  'loyalty reward earned',
  'salary deposit',
  'bank deposit received',
  'freelance payment received',
  'client payment received',
  'interest income',
  'scholarship',
  'annuity',
  'retirement income',
  'remittance',
  'foreign remittance',
  'international transfer received',
  'esewa received',
  'khalti received',
  'ime pay received',
  'connectips credit',
  'labh',
  'munafa',
  'talab',
  'tirtha',
];

export const INCOME_MEDIUM_KEYWORDS = [
  'income',
  'earnings',
  'profit',
  'invoice',
  'freelance income',
  'client income',
  'income earned',
];

export const EXPENSE_HIGH_KEYWORDS = [
  'rent',
  'groceries',
  'grocery',
  'electricity',
  'internet',
  'fuel',
  'transport',
  'restaurant',
  'takeaway',
  'insurance',
  'health insurance',
  'medical',
  'doctor',
  'dentist',
  'hospital',
  'pharmacy',
  'utility',
  'utilities',
  'bill',
  'mortgage',
  'loan repayment',
  'loan emi',
  'home loan emi',
  'interest charge',
  'account interest charge',
  'security deposit',
  'security deposit held',
  'supermarket',
  'petrol',
  'gas',
  'parking',
  'toll',
  'subscription',
  'netflix',
  'spotify',
  'amazon',
  'lease payment',
  'foodmart',
  'bhatbhateni',
  'bigmart',
  'nea',
  'nea bill',
  'water bill',
  'internet bill',
  'wifi',
  'broadband',
  'worldlink',
  'subisu',
  'vianet',
  'cg telecom',
  'diesel',
  'gas station',
  'cafe',
  'dining',
  'food delivery',
  'foodmandu',
  'clinic',
  'medicine',
  'health',
  'school fee',
  'tuition',
  'college fee',
  'university fee',
  'insurance premium',
  'beema',
  'life insurance',
  'taxi',
  'uber',
  'pathao',
  'bus fare',
  'youtube premium',
  'mobile recharge',
  'sim recharge',
  'ncell',
  'ntc',
  'namaste',
  'shopping',
  'daraz',
  'clothing',
  'maintenance',
  'repair',
  'service charge',
  'parking fee',
  'khalti payment',
  'esewa payment',
  'fonepay debit',
  'daraz payment',
  'kharcha',
  'bhuktani',
];

export const EXPENSE_MEDIUM_KEYWORDS = [
  'food',
  'coffee',
  'clothes',
  'accessories',
  'gym',
  'tax',
  'fee',
  'charge',
  'hardware',
  'furniture',
  'equipment',
  'supplies',
  'printing',
  'postage',
  'courier',
  'education',
  'school',
  'childcare',
  'pet',
  'vet',
  'cleaning',
  'laundry',
  'haircut',
  'beauty',
  'travel',
  'hotel',
  'accommodation',
  'airfare',
  'flight',
  'ticket',
  'entertainment',
  'cinema',
  'dinner',
  'trip',
];
